### ISSUE TITLE
What c# version are you using?

### ISSUE THREAD

**Issue by SebastianStehle** [MikePopoloski/SharpBgfx#1]
Hi, what C# version are you using? I dont know this kind of expressions:

public override string ToString () => $"Handle: {handle}";

Do I need vs 2015?

**Comment by MikePopoloski** [comment]
Yeah, I was trying out the new C# language features for fun. You either need VS 2015 or you can make a few edits to remove the usage of the new features. They're pretty straightforward.

**Comment by sbarisic** [comment]
They are also annoying, each project requires over 100 changes just to compile it. I'd suggest making a new release on each commit.

https://github.com/MikePopoloski/SharpBgfx/releases

**Comment by MikePopoloski** [comment]
I updated the code to compile under C# 4 syntax rules.

I'd rather not provide binary releases, because that would require figuring out how to bundle the native DLL nicely and it's easier for the end user to just plop the SharpBgfx.cs file into a project and go.
