### ISSUE TITLE
SharpBgfx and WPF 

### ISSUE THREAD

**Issue by PetrMahdalicek** [MikePopoloski/SharpBgfx#10]
Hi, 
is here anyone who used SharpBgfx in WPF or UWP application? If yes, please share your experience...

**Comment by MikePopoloski** [comment]
Unfortunately as you can see nobody is really doing this sort of thing with WPF. I don't think it would be impossible though; I remember WPF having a D3DImage control that exposes a D3D backbuffer. You could pass this in to bgfx via the PlatformData structure and then force it to start up in D3D9 mode, which would probably work.
