### ISSUE TITLE
VertexLayout.HasAttribute: wrong comparasion

### ISSUE THREAD

**Issue by PowerStateFailure** [MikePopoloski/SharpBgfx#12]
There should be 
`return ptr->Attributes[(int)attribute] != UInt16.MaxValue;`
instead of
`return ptr->Attributes[(int)attribute] != 0xFF;`

See [https://github.com/bkaradzic/bgfx/blob/master/src/vertexdecl.cpp#L162](https://github.com/bkaradzic/bgfx/blob/master/src/vertexdecl.cpp#L162)

**Comment by MikePopoloski** [comment]
Nice catch. I'll get that fixed up when I get a chance.
