### ISSUE TITLE
Compile Shaders via MSBuild (Pull Request Offer)

### ISSUE THREAD

**Issue by smack0007** [MikePopoloski/SharpBgfx#15]
I would like to propose creating an MSBuild script (SharpBgfx.targets) which can be included in projects to automatically compile all shaders via the bgfx shaderc tool. This will mean the shaders can be recompiled whenever the project itself gets recompiled. This would be useful for the example projects as well as it's one less step before you can press F5 in Visual Studio.

The .targets file could eventually be extended to also compile textures as well.

I'm willing to implement this myself but would like to check that this is a direction the project would like to head in before putting in the effort.

**Comment by MikePopoloski** [comment]
Sure, that sounds cool. I'd accept such a pull request if you want to write it.

**Comment by smack0007** [comment]
Cool. I'll take a shot at this after my vacation next week.

**Comment by smack0007** [comment]
I've opened up a pull request: https://github.com/MikePopoloski/SharpBgfx/pull/17

**Comment by MikePopoloski** [comment]
Closing this in favor of keeping discussion in the pull request.
