### ISSUE TITLE
Callback example doesn't seem to work

### ISSUE THREAD

**Issue by raizam** [MikePopoloski/SharpBgfx#18]
Hi, 

The callback example seems to be crashing on the native side, my guess is that the C callback interface has changed at some point and the memory layout doesn't match anymore.

Also, I have updated bgfx on my side (and added bgfx_vsnprintf), but then the instancing example don't work anymore, as the signature of bgfx::allocInstanceDataBuffer has changed.

Also It would be nice to upgrade to .NET Core 2.0, to enable mixed mode debugging

**Comment by MikePopoloski** [comment]
In general you can't just build your own bgfx binary and expect it to work with SharpBgfx without modification. You have to go through each commit that has been made to bgfx in the mean time and make sure it hasn't affected binary compatibility.

I've updated to the latest commit as of yesterday, so your issue should be fixed I think.

**Comment by raizam** [comment]
thanks a lot! 
keep up the good work, this project is a gem
