### ISSUE TITLE
Distribution via nuget-packages

### ISSUE THREAD

**Issue by Trapov** [MikePopoloski/SharpBgfx#21]
> The easiest way to use it is to drop the amalgamated SharpBgfx.cs file into your project and go. Alternatively, you can build the library into a managed assembly.

Wouldn't it be better to publish it as a nuget-package?

**Comment by MikePopoloski** [comment]
For some definition of "better", perhaps. Last I looked distributing architecture-specific binaries alongside a nuget package was annoying and/or impossible. Either way I'm not super interested in doing that work right now, but if you wanted to do it feel free.
