### ISSUE TITLE
Generated bgfx bindings

### ISSUE THREAD

**Issue by raizam** [MikePopoloski/SharpBgfx#25]
Hi,
I've automated generation of [raw bgfx pinvokes](https://gist.github.com/raizam/ac43a3cf4a6259b7e09ece3a1e82068e) directly from bgfx C99 header. It's still WIP and not tested yet at all, but it's starting to take shape. 
Is this something you may be interested for sharpbgfx?

**Comment by MikePopoloski** [comment]
I'm sure that's a useful thing in general, but for this project writing the pinvokes is by far the easiest and least time consuming part of maintaining the library. I don't think the generator would save me much effort.

**Comment by raizam** [comment]
I'm making this project to write a smart pinvoke generator based on Clang.
Currently it scans every functions, extract types recursively from arguments, look at what cpp call is underneath, extract the original cpp function name and documentation...

So yes, it would save you a lot maintenance effort :)

**Comment by raizam** [comment]
problem is that using generated pinvokes would be such a change that most of SharpBgfx would need to be rewritten, it would make more sense to write a new library. so this is why I've closed this issue.
