### ISSUE TITLE
Wrong declaration of bgfx_update_texture_cube

### ISSUE THREAD

**Issue by PowerStateFailure** [MikePopoloski/SharpBgfx#26]
You certainly have misplaced second and third argument in `bgfx_update_texture_cube`: it should've been `handle, layer, stride, ...`, not `handle, stride, layer, ...`. See https://github.com/bkaradzic/bgfx/blob/master/include/bgfx/c99/bgfx.h#L852

(I've spent couple of hours trying to understand why cubemap doesn't work)

**Comment by MikePopoloski** [comment]
Indeed, sorry about that. Fixed !
