### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by RUSshy** [MikePopoloski/SharpBgfx#27]
Hello,

In a .net core project, hello world takes insane amount of memory

![taskmgr_2018-10-14_11-53-27](https://user-images.githubusercontent.com/18348637/46915147-de3fa080-cfa7-11e8-9167-d76944ee2d2a.png)

Version from master

**Comment by MikePopoloski** [comment]
The init settings struct had a misaligned field, which caused it to ask bgfx to allocate a zillion transient index buffer entries. I fixed the issue, thanks for reporting.
