### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by hanbim520** [MikePopoloski/SharpBgfx#29]
Hello, Bgfx has been compiled in OSX, but using your project can not be compiled on OSX and found no OSX target.
<img width="1440" alt="screen shot 2019-01-06 at 1 19 05 pm" src="https://user-images.githubusercontent.com/7490792/50732405-b4b4a080-11b5-11e9-818b-fc2e7a74a14c.png">

**Comment by MikePopoloski** [comment]
You need to rebuild the tool binaries as well, such as shaderc.exe. That of course cannot run on OSX.
