### ISSUE TITLE
Rename bgfx_vertex_decl_* to bgfx_vertex_layout_* ?

### ISSUE THREAD

**Issue by WenceyWang** [MikePopoloski/SharpBgfx#37]
I have found that in bgfx, there is `bgfx_vertex_layout_*` , and in NativeMethods.cs, the pinvoke is `bgfx_vertex_decl_*`. which cause System.EntryPointNotFoundException in my custom built WinRT dll.

**Comment by MikePopoloski** [comment]
SharpBgfx hasn't been updated in about a year, so probably there are a bunch of changes that would need to be reconciled. This is just one of them.
