### ISSUE TITLE
Crash when running hello world in debug mode

### ISSUE THREAD

**Issue by xaviergonz** [MikePopoloski/SharpBgfx#9]
In release mode it works fine, but on debug mode, while trying to run the hello world sample it crashes in Bgfx.cs line 224:

```
            NativeMethods.bgfx_init(
                backend,
                (ushort)adapter.Vendor,
                (ushort)adapter.DeviceId,
                CallbackShim.CreateShim(callbackHandler),
                IntPtr.Zero
            );
```

**Comment by MikePopoloski** [comment]
I believe this is from bgfx issue: https://github.com/bkaradzic/bgfx/issues/925

I haven't gotten around to doing a new build with the fix.

**Comment by raizam** [comment]
I've rebuilt bgfx,tried to run the examples, and I'm having a BadImageFormatException on `NativeMethods.bgfx_set_platform_data(ref data);`
(called from SetWindowHandle).
The PlatformData structure may have changed?

**Comment by MikePopoloski** [comment]
That's the first call made into bgfx though right? Did you build a DLL for the correct platform (x64) ?

**Comment by MikePopoloski** [comment]
I just updated binaries. Let me know if that resolves the issue for you.

**Comment by raizam** [comment]
works great thanks!
Is there any plans to integrate nanovg and/or imgui ?

**Comment by MikePopoloski** [comment]
I'd like to do imgui at some point but it's a large project.

**Comment by raizam** [comment]
a large project as you say...
you know what? I'm stuck trying to choose between Monogame, and this project to assemble some game engine. and I feel like whatever I choose, a very long path is ahead.

**Comment by MikePopoloski** [comment]
Yep, welcome to game development my friend :)
